spring:
  mail:
    host: smtp.googlemail.com
    port: 587
    username: medboulaamail@gmail.com
    password: yoxk admg whfd vsvv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/petstore
    username: postgres
  application:
    name: authentication-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  data:
    mongodb:
      port: 27017
      host: localhost
      database: pets
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: -1
      max-request-size: -1
